-- ============================================================
--  CRM New Beginning — schemat bazy (Supabase / Postgres)
--  Wklej całość w Supabase -> SQL Editor -> Run (jednorazowo).
--  Prosto: 2 tabele (clients, comments). Własność kart = UMOWNA
--  (każdy zalogowany może edytować — granicę pilnuje aplikacja + zasada w zespole).
-- ============================================================

create table if not exists clients (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  company     text,
  phone       text,
  email       text,
  google_maps text,
  quality     text,
  status      text not null default 'lead',   -- lead | zainteresowany | umowiony | po_spotkaniu | oferta | konwersja  (Archiwum = deleted_at, nie status)
  follow_up   date,
  owner       text not null,                  -- imię właściciela: Krzysztof | Marceli | Szymon | Bartek | Piotr
  notes       text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create table if not exists comments (
  id         uuid primary key default gen_random_uuid(),
  client_id  uuid references clients(id) on delete cascade,
  author     text not null,
  body       text not null,
  created_at timestamptz default now()
);

-- Zespół: lista członków. Rośnie sama — gdy ktoś nowy (dodany w panelu Supabase
-- Authentication -> Add user) pierwszy raz się zaloguje, aplikacja dopisuje go tutaj.
create table if not exists team_members (
  id         uuid primary key default gen_random_uuid(),
  email      text unique not null,
  name       text not null,
  created_at timestamptz default now()
);

create index if not exists idx_comments_client on comments(client_id);
create index if not exists idx_clients_owner on clients(owner);

-- ============================================================
--  RLS — bezpieczeństwo: dostęp TYLKO dla zalogowanych członków zespołu.
--  (Publiczny anon key nie wystawia danych światu — bez logowania nic nie widać.)
-- ============================================================
alter table clients      enable row level security;
alter table comments     enable row level security;
alter table team_members enable row level security;

create policy "zespol_odczyt_clients"  on clients      for select to authenticated using (true);
create policy "zespol_zapis_clients"   on clients      for all    to authenticated using (true) with check (true);
create policy "zespol_odczyt_comments" on comments     for select to authenticated using (true);
create policy "zespol_zapis_comments"  on comments     for all    to authenticated using (true) with check (true);
create policy "zespol_odczyt_team"     on team_members for select to authenticated using (true);
create policy "zespol_zapis_team"      on team_members for all    to authenticated using (true) with check (true);

-- ============================================================
--  v2 (2026-06-21): "Poproś o demo" + realtime
-- ============================================================
alter table clients add column if not exists demo_requested boolean default false;

create table if not exists demo_requests (
  id          bigint generated by default as identity primary key,
  client_id   uuid references clients(id) on delete cascade,
  requested_by text not null,
  note        text,
  status      text not null default 'pending',  -- pending | done
  created_at  timestamptz default now()
);
alter table demo_requests enable row level security;
create policy "team_read_demo"  on demo_requests for select to authenticated using (true);
create policy "team_write_demo" on demo_requests for all    to authenticated using (true) with check (true);

-- realtime (live podgląd zmian u wszystkich)
alter publication supabase_realtime add table clients;
alter publication supabase_realtime add table comments;
alter publication supabase_realtime add table demo_requests;

-- ============================================================
--  v3 (2026-06-21): ARCHIWUM / soft-delete (chowanie odwracalne)
--  deleted_at NULL = karta aktywna; data = karta w Archiwum (schowana z tablicy, do przywrócenia).
--  "Przenieś do archiwum" w UI ustawia deleted_at; "Przywróć" zeruje; "Usuń trwale" robi DELETE.
-- ============================================================
alter table clients add column if not exists deleted_at timestamptz default null;
create index if not exists idx_clients_deleted_at on clients(deleted_at);
