-- ============================================================
--  CRM Impulseo — UMOWY (przycisk „Stwórz umowę" na karcie klienta)
--  Handlowiec wypełnia krótki formularz → wpis trafia tutaj → automat
--  składa PDF z zatwierdzonego wzoru i odkłada go do Storage → na karcie
--  pojawia się gotowy plik do pobrania i wrzucenia do Autenti.
--  Wklej całość w Supabase -> SQL Editor -> Run (jednorazowo).
--
--  ✅ BEZPIECZNE — addytywne i idempotentne (można wielokrotnie).
--     Nie rusza żadnej istniejącej tabeli ani polityki.
--  ⚠️ WYMAGA wcześniejszego schema-rbac.sql (część A) — polityki używają
--     public.authorize() i public.my_name() (plik sam się zatrzyma, gdy ich brak).
--
--  ↩️ JAK COFNĄĆ:
--     drop table if exists public.contracts;
--     delete from storage.buckets where id = 'umowy';        -- skasuje też pliki PDF
--     delete from public.role_permissions where perm_key = 'contracts.create';
--     delete from public.permissions where key = 'contracts.create';
-- ============================================================

begin;

-- Bezpiecznik: bez części A RBAC zatrzymaj się teraz (transakcja się wycofa).
do $$
begin
  if to_regprocedure('public.authorize(text)') is null
     or to_regprocedure('public.my_name()') is null then
    raise exception 'Najpierw wykonaj schema-rbac.sql (część A) — brak public.authorize()/public.my_name().';
  end if;
end;
$$;

-- ============================================================
--  1. TABELA UMÓW
--     Trzymamy KOMPLET danych z formularza (nie tylko gotowy plik), żeby
--     dało się wygenerować umowę ponownie — np. po poprawce we wzorze albo
--     gdy handlowiec pomylił kwotę i robi wersję poprawioną.
--     status: pending (czeka na automat) | ready (PDF gotowy) | error (nie wyszło)
-- ============================================================
create table if not exists contracts (
  id            bigint generated by default as identity primary key,
  client_id     uuid not null references clients(id) on delete cascade,
  created_by    text not null,                    -- imię handlowca (jak comments.author)
  status        text not null default 'pending' check (status in ('pending', 'ready', 'error')),

  -- dane wpisane w formularzu
  klient_nazwa  text not null,
  klient_adres  text not null,
  klient_nip    text not null,
  klient_krs    text,                              -- puste = wzmianka o KRS znika z umowy
  klient_email  text not null,
  klient_repr   text,                              -- puste = wzmianka o reprezentancie znika
  kwota_strona  numeric not null check (kwota_strona >= 0),
  kwota_abon    numeric not null check (kwota_abon  >= 0),
  abonament     text not null check (abonament in ('rok_zgory', 'rok_mies', 'polrok_mies')),
  nasz_repr     text not null check (nasz_repr in ('krzysztof', 'marceli')),  -- kto podpisuje po naszej stronie
  data_umowy    date not null default current_date,

  -- wynik pracy automatu
  pdf_path      text,                              -- ścieżka pliku w buckecie 'umowy'
  error_msg     text,
  created_at    timestamptz default now(),
  ready_at      timestamptz
);

create index if not exists idx_contracts_client on contracts(client_id);
create index if not exists idx_contracts_status on contracts(status);

-- ============================================================
--  2. UPRAWNIENIE — kto w ogóle może tworzyć umowy
--     Domyślnie dostaje je 'sprzedawca' (admin ma wszystko niejawnie).
--     Gdyby kiedyś miało to być zawężone — wystarczy odhaczyć w panelu admina.
-- ============================================================
insert into permissions (key, label, grp, ord) values
  ('contracts.create', 'Tworzy umowy z karty klienta', 'Klienci', 60)
on conflict (key) do nothing;

insert into role_permissions (role_key, perm_key) values
  ('sprzedawca', 'contracts.create'),
  ('developer',  'contracts.create')
on conflict do nothing;

-- ============================================================
--  3. KOMU WOLNO CO — RLS
--     Zasada Krzysztofa: „każdy handlowiec do swoich klientów".
--     Widzisz umowę wtedy, kiedy widzisz kartę klienta, czyli gdy jesteś
--     jej handlowcem (owner) albo opiekunem — chyba że masz 'clients.view_all'.
-- ============================================================
alter table contracts enable row level security;

-- pomocnik: czy widzę kartę tego klienta (ta sama zasada, co w aplikacji)
create or replace function public.moj_klient(cid uuid)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.clients c
     where c.id = cid
       and ( (select public.authorize('clients.view_all'))
             or c.owner   = (select public.my_name())
             or c.opiekun = (select public.my_name()) )
  );
$$;

drop policy if exists "umowy_odczyt" on contracts;
create policy "umowy_odczyt" on contracts for select to authenticated
  using ((select public.moj_klient(client_id)));

drop policy if exists "umowy_dodanie" on contracts;
create policy "umowy_dodanie" on contracts for insert to authenticated
  with check (
    (select public.authorize('contracts.create'))
    and (select public.moj_klient(client_id))
    and created_by = (select public.my_name())      -- nie podpiszesz się cudzym imieniem
  );

-- Wypełnianie pdf_path/status robi automat kluczem serwisowym (omija RLS),
-- dlatego zwykły użytkownik NIE dostaje prawa update — nie podmieni gotowego pliku.
drop policy if exists "umowy_kasowanie" on contracts;
create policy "umowy_kasowanie" on contracts for delete to authenticated
  using ((select public.authorize('clients.hard_delete')));

-- ============================================================
--  4. MIEJSCE NA PLIKI — prywatny bucket 'umowy'
--     Prywatny = nikt z ulicy nie pobierze pliku po adresie. CRM prosi
--     o czasowy link (signed URL), a Supabase go wystawi tylko wtedy,
--     gdy proszący widzi odpowiadającą umowę (polityka niżej).
-- ============================================================
insert into storage.buckets (id, name, public)
values ('umowy', 'umowy', false)
on conflict (id) do nothing;

drop policy if exists "umowy_plik_odczyt" on storage.objects;
create policy "umowy_plik_odczyt" on storage.objects for select to authenticated
  using (
    bucket_id = 'umowy'
    and exists (
      select 1 from public.contracts u
       where u.pdf_path = storage.objects.name
         and (select public.moj_klient(u.client_id))
    )
  );

-- realtime: gotowy PDF ma się pokazać na karcie sam, bez odświeżania strony
do $$
begin
  alter publication supabase_realtime add table contracts;
exception when duplicate_object then null;
end;
$$;

commit;
